"""empty message

Revision ID: 9554db791ba3
Revises: 0c4dc332ad8f
Create Date: 2021-06-21 06:49:03.287477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9554db791ba3'
down_revision = '0c4dc332ad8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Venue', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Artist', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
